# Generated by Django 3.2.12 on 2022-03-31 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20220331_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='menu.menudate'),
        ),
    ]
