# Generated by Django 3.2.12 on 2022-03-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_menu_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_date',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_date',
            field=models.ManyToManyField(blank=True, related_name='menus', to='menu.MenuDate'),
        ),
    ]
