# Generated by Django 3.2.12 on 2022-04-05 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menu_created'),
        ('customer', '0001_initial'),
        ('orders', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='menu.menu'),
        ),
    ]
