# Generated by Django 3.2.12 on 2022-04-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220405_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ref',
            field=models.CharField(default='AA', max_length=50, unique=True),
        ),
    ]
